package com.hospital.security.authorization;

import com.hospital.security.jwt.PatientAuthenticationDetails;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Helper class for accessing Spring Security context.
 * Provides utility methods for getting current user and checking roles.
 */
@Component
public class SecurityContextHelper {

    /**
     * Get the username of the currently authenticated user.
     *
     * @return the username, or "anonymous" if not authenticated
     */
    public static String getCurrentUsername() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth == null || !auth.isAuthenticated()) {
            return "anonymous";
        }
        return auth.getName();
    }

    /**
     * Check if the current user has a specific role.
     *
     * @param role the role name (without ROLE_ prefix)
     * @return true if user has the role, false otherwise
     */
    public static boolean hasRole(String role) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth == null) {
            return false;
        }
        return auth.getAuthorities().stream()
                .anyMatch(a -> a.getAuthority().equals("ROLE_" + role));
    }

    /**
     * Extract the patientBusinessId from the current JWT token details.
     * Only populated for PATIENT role tokens generated by JwtTokenProvider.generatePatientToken().
     *
     * @return patientBusinessId UUID string, or null if not a patient token
     */
    public static String getPatientBusinessId() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getDetails() instanceof PatientAuthenticationDetails patientDetails) {
            return patientDetails.getPatientBusinessId();
        }
        return null;
    }
}
