package com.hospital.security.jwt;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.security.web.authentication.WebAuthenticationDetails;

/**
 * Extended authentication details for patient portal tokens.
 * Carries the patientBusinessId from the JWT claim alongside the standard WebAuthenticationDetails.
 * Only populated for tokens generated by JwtTokenProvider.generatePatientToken().
 */
public class PatientAuthenticationDetails extends WebAuthenticationDetails {

    private final String patientBusinessId;

    public PatientAuthenticationDetails(HttpServletRequest request, String patientBusinessId) {
        super(request);
        this.patientBusinessId = patientBusinessId;
    }

    public String getPatientBusinessId() {
        return patientBusinessId;
    }
}
